### ISSUE TITLE
Auth store: Error: Exported variable from external module but cannot be named. (TS 4023)

### ISSUE THREAD

**Issue by tvld** [marshallswain/feathers-pinia#100]
Auth store needed typing to avoid Typescript error: TS4023

``Exported variable from external module but cannot be named.ts(4023)``

```ts
import { type StoreDefinition, defineStore, acceptHMRUpdate } from 'pinia'  //  >>>> Type StoreDefiniton
import { useAuth } from 'feathers-pinia'

// export const useAuthStore = defineStore('auth', () => {  //  >>>> Gives TS4023
export const useAuthStore: StoreDefinition = defineStore('auth', () => {  //  >>>> Type StoreDefiniton
  const { userStore } = useUserStore()
  const { $api } = useFeathers()

  const auth = useAuth({
    api: $api,
    userStore
  })

  auth.reAuthenticate()

  return auth
})
```

**Comment by marshallswain** [comment]
Such a strange error.  I've experienced it a few times during the Feathers-Pinia rewrite.  Thanks for reporting.

**Comment by marshallswain** [comment]
This issue seems to be fixed, now. I'll close for now, but if it comes up again let me know, and we can try to pin it down.

![Screenshot 2023-01-02 at 11 07 30 PM](https://user-images.githubusercontent.com/128857/210307236-4ef01659-64e3-48b1-9551-bb053333552e.jpg)

**Comment by marshallswain** [comment]
The above project is using `"feathers-pinia": "^2.0.0-pre.6",`
