### ISSUE TITLE
useClones throws undefined error when hit with a server error 

### ISSUE THREAD

**Issue by philipimperato** [marshallswain/feathers-pinia#102]
The `saved` var is undefined and the `clone()` method is called on it

https://cdn.discordapp.com/attachments/930351539804065842/1054894897146122351/image.png

**Comment by marshallswain** [comment]
Thanks for reporting this.  I'll address it soon.

**Comment by philipimperato** [comment]
@marshallswain I believe this should be closed.

**Comment by marshallswain** [comment]
Yes. Thanks!
