### ISSUE TITLE
TypeError: Cannot destructure property 'defaultSkip' of 'e2.pagination' as it is undefined

### ISSUE THREAD

**Issue by philipimperato** [marshallswain/feathers-pinia#105]
When accessing `useFind` from the Model with `onServer: false`, calling the `find()` pulls from the server but does not return anything from the store.

When using `onServer: true` I get this error: 
![image](https://user-images.githubusercontent.com/2430560/210617891-be16de0a-73ae-4b20-8a31-7e145ef9e001.png)

Ref: https://github.com/marshallswain/feathers-pinia/blob/v2/src/utils.ts#L240

When doing the same call from `Model.store.useFind` all things work as expected. I found this out as the `store.pagination` doesn't exist on the Model. 

I'm thinking, either `useFind` shouldn't be a method on the model or a store instance has to be conditional?

**Comment by marshallswain** [comment]
Model.useFind wasn't providing the store in the params.  This should be fixed in pre.13.  Please reopen if you find otherwise.
