### ISSUE TITLE
createClient for non dove api users

### ISSUE THREAD

**Issue by ericuldall** [marshallswain/feathers-pinia#109]
Can we get an example of createClient for users who are not on feathers api v5?

**Comment by marshallswain** [comment]
Yes!  There is one in the Common Patterns section, here: https://v2.feathers-pinia.pages.dev/guide/common-patterns.html#feathers-clients-manual-setup

It would be good to refactor it to be called `createClient`, like you mention.  Can you point me to a specific place it would be valuable to link to the common patterns page?  It seems likely that we need another link that points there.

**Comment by ericuldall** [comment]
I read that, I think maybe I was thrown off (not sure why, maybe just a typo) but I think:

```
import { feathers } from '@feathersjs/feathers'
```

Should be

```
import feathers from '@feathersjs/feathers'
```

I ended up just looking at my original working implementation from feathers-vuex and got it working tho. Slowly starting to learn all the new conventions. :D

**Comment by ericuldall** [comment]
RE: Where to put it in docs
<img width="734" alt="image" src="https://user-images.githubusercontent.com/3223296/214962688-f04d3ddc-0dd4-4635-8618-242ba51106c7.png">

It should be another tab there.

**Comment by marshallswain** [comment]
The 3.0 docs have great client docs, now.
