### ISSUE TITLE
Feature request: Add ability to pass params to saveHandler.

### ISSUE THREAD

**Issue by gustojs** [marshallswain/feathers-pinia#11]
Using handleClones, the save handler sends the data to patch, but we can't provide params as an argument.

An example use case: 

When we use **feathers-graphql-populate**, this leads to the returned value being merged to the store without populated data, because we didn't pass `$populateParams` for the patch event.

**Comment by marshallswain** [comment]
Support for params is now published in `feathers-pinia@0.18.0`.  

Read docs, here: https://feathers-pinia.pages.dev/guide/handle-clones.html#save-handler-params
