### ISSUE TITLE
useFind not returning data

### ISSUE THREAD

**Issue by ericuldall** [marshallswain/feathers-pinia#110]
I'm trying to useFind from a feathersModel and I can see the result getting returned on my feathers api side but I can't access it in Vue.

Here's my sample code:
```
const pagination = reactive({ $limit: 10, $skip: 0 })
const params = computed(() => {
  return {
    query: {
      ...pagination,
      askedDate: {
        $gt: moment().format('YYYY-MM-DD')
      }
    },
    onServer: true,
  }
})
const Question = useQuestionModel();
const { data, find, prev, next } = Question.useFind(params);
console.log('data', data);
```

Data has no value in that example. Is there something i'm missing?

**Comment by ericuldall** [comment]
This is weird.. If I do this:
```
const questions = ref(Question.useFind(params));
```

Then in my template:
```
{{ JSON.stringify(questions) }}
```

The data are there... I clearly have no idea how this is supposed to work :D

**Comment by ericuldall** [comment]
After digging a bit deeper. It seems data is empty, allData is empty, but response.data has my query results. However, my understanding is that data should be available in the root data property. Is there some reason that's not making it there?

**Comment by ericuldall** [comment]
Another reference, the following code works as expected:
```
const Question = useQuestionModel();
const questions = ref([]);
Question.find(params).then(res => {
    questions.value = res;
});
```

**Comment by philipimperato** [comment]
My gut says that the date format is throwing off the query to the store. Maybe try `toISOString()`?

**Comment by ericuldall** [comment]
no .toISOString method on there, but I used .toString and still no result

**Comment by ericuldall** [comment]
@ marshallswain any thoughts on this? I've gone through setup in 2 different projects and useFind doesn't work as expected.
