### ISSUE TITLE
syncWithStorage not being auto imported

### ISSUE THREAD

**Issue by ericuldall** [marshallswain/feathers-pinia#115]
For some reason I'm not getting syncWithStorage to work with auto import. Here's my vite config:

```
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import AutoImport from 'unplugin-auto-import/vite'
import { feathersPiniaAutoImport } from 'feathers-pinia'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), AutoImport({
    include: [
      /\.[tj]sx?$/, // .ts, .tsx, .js, .jsx
      /\.vue$/, /\.vue\?vue/, // .vue
      /\.md$/, // .md
    ],
    imports: [
      'vue',
      'vue-router',
      feathersPiniaAutoImport
    ],
    dts: true,
    dirs: ['src/composables', 'src/models', 'src/stores'],
    vueTemplate: true,
  })],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})
```

Any ideas on this?

**Comment by ericuldall** [comment]
Looks like it's just missing in this file: https://github.com/marshallswain/feathers-pinia/blob/v2/src/unplugin-auto-import-preset.ts

**Comment by marshallswain** [comment]
Thanks for reporting.  Yeah, I was still doing an audit of the status of the `syncWithStorage` plugin, and comparing it to other localStorage plugins available for Pinia.  I like to reuse stuff from the Vue community if it's superior, but in this case the `syncWithStorage` plugin actually wins for brevity and flexibility.

FYI, in feathers-pinia version 3 I'm going to bake `syncWithStorage` in so there will be no need to import it.  You'll specify the keys you want cached in the config and it will take care of the rest.  Stores are created implicitly in version 3, so it's all handled under the hood.  Project setup goes from a few files of boilerplate per service to about 10 lines of code.  It's what I've wanted all along, but it took a while to figure out how to accomplish it with Pinia.

**Comment by ericuldall** [comment]
This works in v3. closing
