### ISSUE TITLE
"Error: Failed to execute 'fetch' on 'Window': Illegal Invocation. When authenticate-ing

### ISSUE THREAD

**Issue by danielenriquez59** [marshallswain/feathers-pinia#123]
When I hit this line in my code,     
await authStore.authenticate({strategy: 'local', ...state})

I get the error below
![image](https://user-images.githubusercontent.com/67985535/231553345-4089cfd9-e65d-4c53-9cc1-3b9a40ab4f41.png)

any thoughts?

**Comment by danielenriquez59** [comment]
Heres my feathers.js file: 
`import { feathers } from "@feathersjs/feathers";
import authenticationClient from "@feathersjs/authentication-client";
import rest from "@feathersjs/rest-client";
import { pinia } from "@/store/index";
import { createPiniaClient } from "feathers-pinia";

const host = import.meta.env.VITE_API_URL || "http://localhost:3030";
window.fetch.bind(window);

export const feathersClient = feathers()
  .configure(rest(host).fetch(fetch))
  .configure(authenticationClient({ storage: window.localStorage }));

// src/feathers.ts
export const api = createPiniaClient(feathersClient, {
    pinia,
    idField: "_id",
    // optional
    ssr: false,
    whitelist: [],
    paramsForServer: [],
    skipGetIfExists: true,
    customSiftOperators: {},
    services: {},
  });`

**Comment by danielenriquez59** [comment]
using ofetch fixed this issue for me. https://v3.feathers-pinia.pages.dev/setup/nuxt3.html#_1-feathers-client

**Comment by marshallswain** [comment]
I found the fix for the original configuration. Change this line:

```
window.fetch.bind(window);
```

to this:

```
const fetch = window.fetch.bind(window);
```

You have to pass the bound `fetch` to the fetch client.
