### ISSUE TITLE
Module does not provide an export named 'useClones'

### ISSUE THREAD

**Issue by vicentecastroa** [marshallswain/feathers-pinia#127]
Package version: 3.0.2

I'm following the guide for [useClones](https://feathers-pinia.pages.dev/guide/use-clones.html#basic-setup) and I'm failing into an error that says "...modules does not provide an export named 'useClones'" 
I looked into the source code and I couldn't find the definition for `useClones`. Am I doing something wrong?
![image](https://github.com/marshallswain/feathers-pinia/assets/13738469/55c92a18-2f4a-4b0a-9043-23913a2666b5)

**Comment by itoonx** [comment]
I got this error after i have upgrade to version 3.0.2

**Comment by 1sses** [comment]
I read somewhere in docs that useClones was removed from API (with comment "just use model.clone()")

**Comment by marshallswain** [comment]
@1sses is correct.  The functionality previously available in `useClones` in versions 1 and 2 was integrated into the service methods, so you can just call .clone.
