### ISSUE TITLE
The defineStore() wrapper expects state to be an object and not a function like pinia

### ISSUE THREAD

**Issue by miguelrk** [marshallswain/feathers-pinia#14]
### Context:
**pinia:** the native `defineStore()` method requires state to be a function which returns an object e.g. `state: () => ({...})`.

**feathers-pinia:** the `defineStore()` method expects an object directly e.g. `state: {...}`.

### Problem:
Developers can easily forget to pass an object causing store state to not be merged correctly.

### Solution:
The feathers-pinia `defineStore()` wrapper should also only expect a function so that the wrapper can pass the options 'as is' to the original `defineStore()`.

**Comment by marshallswain** [comment]
Released as `feathers-pinia@0.19.0`.  Thanks for finishing it up!
