### ISSUE TITLE
Warnings with types

### ISSUE THREAD

**Issue by Granipouss** [marshallswain/feathers-pinia#143]
Hey,

I am trying to use feather-pinia v4 with feathersjs v5.
But I have some typescript warnings in vscode.

```ts
import { client } from '@/feathersClient'
import { createPiniaClient } from 'feathers-pinia'
import { getActivePinia } from 'pinia'

export const api = createPiniaClient(client, {
  pinia: getActivePinia(),
  idField: '_id'
})
```

It shows me :

```
Exported variable 'api' has or is using name 'AppExtensions' from external module "path/to/node_modules/feathers-pinia/dist/create-pinia-client" but cannot be named.ts(4023)
const api: Application<CreatePiniaServiceTypes<ServiceTypes>, any> & AppExtensions
```

And indeed it seems like types are not exported in `create-pinia-client.ts`

I think that can be resolved by simply ensuring that every type used in exported methods is also exported.

Cheers

**Comment by marshallswain** [comment]
@Granipouss did this issue get resolved by merging your PR?

**Comment by marshallswain** [comment]
I think we're making good progress in this area.  I'm closing this for now.  Feel free to reopen if the issue persists.
