### ISSUE TITLE
default idField as 'id' vs '_id'

### ISSUE THREAD

**Issue by fratzinger** [marshallswain/feathers-pinia#27]
This:
https://github.com/marshallswain/feathers-pinia/blob/19a13eec04605f140c1e5b4f46e13c132c0052d3/src/define-store.ts#L34
vs this:
https://github.com/marshallswain/feathers-pinia/blob/19a13eec04605f140c1e5b4f46e13c132c0052d3/src/service-store/make-state.ts#L15

Currently `_id` is taken by default. Should `_id` be the default?

**Comment by marshallswain** [comment]
Let's keep it the same as feathers Vuex, so use 'id'
