### ISSUE TITLE
add `__isTemp` getter to BaseModel

### ISSUE THREAD

**Issue by fratzinger** [marshallswain/feathers-pinia#29]
`feathers-vuex` has `__isTemp` by `Object.defineProperty`.
`feathers-pinia` does not have it anymore. I use it in `feathers-vuex`. The removement is a breaking change and should be stated in the docs.
oooor we add a getter to the BaseModel:
```ts
get __isTemp() {
  const { idField } = this.constructor as typeof BaseModel
  return getId(this, idField) != null
}
```
Todo:
- [x] add `__isTemp` getter @fratzinger 
- [x] add a test for it (item with `__tempId`, item with `__tempId` and `[idField]`, item with `[idField]` @fratzinger

**Comment by marshallswain** [comment]
Added to `feathers-pinia@0.32.0`.
