### ISSUE TITLE
finish/remove `eventLocksById`

### ISSUE THREAD

**Issue by fratzinger** [marshallswain/feathers-pinia#34]
What is `eventLocksById` for? I saw the mention in the docs and I saw the implementation in the code. As of now it's not used anywhere.

I stumbled upon this while adding types. See this as a friendly reminder to tackle this topic sometimes in the future. If you like to share, I would love to hear your idea behind this.

**Comment by marshallswain** [comment]
I was able to implement event locks in v2.  Thanks!  Closing.
