### ISSUE TITLE
Search breaks starting from version 0.26.0

### ISSUE THREAD

**Issue by laurensiusadi** [marshallswain/feathers-pinia#37]
I'm trying this repo https://github.com/marshallswain/vitesse-feathers-pinia-example
And updating it to latest 0.29.5, the search bar becomes unusable.
Inside devtools, `queryId` is not updating despite the `search.value` changing.
So I downgrade one by one version to find latest working version and that's 0.25.0.
Starting from 0.26.0 the search breaks.
The problem seems to be inside `useFind`. But I can't figure out what yet.

**Comment by laurensiusadi** [comment]
Okay, so I found out we need to either supply `queryWhen` or call `find()` explicitly from 0.25.0+.

**Comment by marshallswain** [comment]
Reactivity for useFind is fixed in `0.29.6`.
