### ISSUE TITLE
Can't resolve vue-demi on fresh install

### ISSUE THREAD

**Issue by AtomicTroop** [marshallswain/feathers-pinia#40]
Vite throws `ERROR: Could not resolve "vue-demi"` when attempting to build a freshly generated Vue project using feathers-pinia.
Initially I ran into this problem when using Vue + feathers-pinia with a custom webpack build process. I thought I might have misconfigured something and attempted again with a fresh project.

These are the steps I took to run into this issue:

I generated a fresh Vue project with `npm init vue@latest` as instructed by Vue's quickstart.
After this, I installed pinia and feathers-pinia with npm. According to the current feathers-pinia documentation, these should be all the required steps to get the library up and running.
I added a feathers-pinia store according to the `store.pinia.ts` code snippet in the setup instructions and added the newly created pinia store to the app with `.use(pinia)`.
At this point, attempting to run `npm run dev` results in the error in question.

**Comment by AtomicTroop** [comment]
A quick read through the vue-demi documentation would indicate that vue-demi should be a dependency rather than a dev dependency in feathers-pinia like it is now.
I'd love to submit a small PR on this but I'm not that familiar with vue-demi so someone more familiar with this project can hopefully verify that this solution would be alright.

**Comment by marshallswain** [comment]
Good catch.  This is fixed in `feathers-pinia@0.29.7`.
