### ISSUE TITLE
Error behavior in useGet

### ISSUE THREAD

**Issue by laurensiusadi** [marshallswain/feathers-pinia#44]
`const { item, error } = useGet({ model, id })`

Bug behavior, error not showing properly
1. Provide invalid id
2. Error showing Not Found ✔
3. Reset error manually `error.value = null`
4. Error is gone
6. Provide invalid id
7. Error not showing Not Found ❌
8. Provide valid id
9. Provide invalid id
10. Error showing Not Found ✔

**Comment by marshallswain** [comment]
Fixed in `feathers-pinia@0.36.2`
