### ISSUE TITLE
idField seemingly ignored on service

### ISSUE THREAD

**Issue by MajesticPotatoe** [marshallswain/feathers-pinia#46]
So after a long amount of trial and error as to why nothing was being added to the store, it seem settings `idField` to any value other than 'id' seems to get ignored.

example code below:
```js
import { defineStore, BaseModel } from '@/plugins/pinia'
import { api } from '@/plugins/feathers'

export class AuthUser extends BaseModel {}

const servicePath = 'users'
export const useAuthUser = defineStore({
  idField: 'userID',
  Model: AuthUser,
  servicePath,
})

api.service(servicePath).hooks({})
```

Results from `get`/`find` return results properly (which can be done by peeking at the results via a hook) but its never added (`getFromStore` / `findInStore` always return 0 records)

Currently just working around this by setting `id` to whatever the fieldID i want on my backend.

**Comment by marshallswain** [comment]
I've added tests to verify that the custom id field works.  This is an older issue, so it may have gotten fixed since April.  Please reopen if you find that it still doesn't work.
