### ISSUE TITLE
when using pagination, queryId is including $client params included with paramsForServer

### ISSUE THREAD

**Issue by ha6755ad** [marshallswain/feathers-pinia#51]
I am using a before hooks in my feathers-client setup where I'm using feathers-hooks-common paramsForServer method to pass whitelisted params to the server. The $client object is being included in the queryId on useFind with pagination:true. 

This is making it so I cannot use pagination because my params object that becomes the queryId never matches the local one being passed as an argument to useFind - because the hook is adding the $client object with paramsForServer.

This is causing some less show-stopping, but obnoxious side effects such as the long accessToken being included in the queryId as well.

**Comment by marshallswain** [comment]
Hmmm.  I designed feathers-pinia to work with the `paramsForServer` hook in [feathers-graph-populate](https://feathers-graph-populate.netlify.app/).  I recommend trying those hooks out, instead.

**Comment by ha6755ad** [comment]
Yes! I forgot there was a naming conflict there. I think I was importing paramsForServer as some alias before upgrading to feathers-pinia and I forgot about the naming conflict. That fixes it.

**Comment by marshallswain** [comment]
Awesome.  Thanks for the update.
