### ISSUE TITLE
Auth Store documentation errors

### ISSUE THREAD

**Issue by engineertdog** [marshallswain/feathers-pinia#53]
The documentation shows an example of being able to get the authenticated user through a getter on the Auth store:
https://feathers-pinia.pages.dev/guide/auth-stores.html#setup

The code referenced is:
```js
const authStore = defineAuthStore({
  feathersClient,
  state: () => ({
    userId: null
  }),
  getters: {
    user() {
      return this.userId ? User.getFromStore(this.userId) : null
    },
  },
  actions: {
    handleResponse(response: any) {
      this.userId = response.user.id || response.user._id
      User.addToStore(response.user)
      return response
    },
  },
})
```

There are a couple of problems with this:

1. `response: any` should be typed appropriately.
2. The getter supplied above, if used as is, will throw Typescript errors for the following reasons:
    * `Property 'userId' does not exist on type '{ user(): any; }'. Did you mean 'user'?`
    * `'user' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.`
4. If you update the getter above to something like the following code, then there are no Typescript errors, but Vue will forcefully redirect you to the login page, even if your token is still valid.
```js
user(): User | null {
      return (this.userId ? User.getFromStore(this.userId) : null) as User | null
}
```

**Comment by emmanuelgeoffray** [comment]
@engineertdog Did you see #35 ?

**Comment by marshallswain** [comment]
Closing this issue in favor of #35.
