### ISSUE TITLE
item.create() does not add id to item after call

### ISSUE THREAD

**Issue by emmanuelgeoffray** [marshallswain/feathers-pinia#54]
After a call to create, item should contain the id returned from server.

To reproduce:

```
const post = New Post({
  name: 'New post'
})
await post.create()
console.log(post.id) // returns undefined
```

Here is a quick fix :

```
let post = New Post({
  name: 'New post'
})
await post.create()
const { data } = postStore.findInStore({
        query: {
          name: 'New post'
        }
})
post = data[0]
console.log(post.id) // ok
```

But it's kind of broken as you could have many posts with the same name.

**Comment by marshallswain** [comment]
I'm surprised this doesn't work.  I'll check into it.

**Comment by marshallswain** [comment]
Oh.  I think I see why it's not working.  `post` is not reactive when initially declared.  It's just a plain JS class instance.

Try this:

```ts
const post = new Post({ name: 'blah' }).addToStore() // reactivity added in the store
await post.create()
console.log(post.id)
```

I think we can make it work both ways, though.

**Comment by marshallswain** [comment]
To avoid extra merges, I'm only going to make this feature work for the `create` method on NON-reactive data (not added to store).  This will at least allow you to utilize the id assigned by the server.  All other interactions will require the use of `.addToStore()` in order to work.

**Comment by marshallswain** [comment]
This is now documented, here: https://feathers-pinia.pages.dev/guide/model-instances.html#instance-addtostore
