### ISSUE TITLE
save('name') feature

### ISSUE THREAD

**Issue by emmanuelgeoffray** [marshallswain/feathers-pinia#55]
As the [`save_handler`](https://feathers-pinia.pages.dev/guide/handle-clones.html#using-the-save-handlers), it would be nice to have a `save('name')` option to send a `PATCH` with an object containing only the mentioned property.

**Comment by marshallswain** [comment]
Good news!  This feature is already built in.  I just haven't updated the documentation, yet.  There are multiple syntaxes already supported.  

- `save(prop)`
- `save([prop1, prop2])`
- `save({ key: value })`

**Comment by marshallswain** [comment]
I'm going to leave this open until I rewrite the docs.

**Comment by marshallswain** [comment]
I believe so.  You can check here: https://github.com/marshallswain/feathers-pinia/blob/main/tests/handle-clones.test.ts

**Comment by marshallswain** [comment]
The array syntax is being tested, here: https://github.com/marshallswain/feathers-pinia/blob/main/tests/handle-clones.test.ts#L45

**Comment by marshallswain** [comment]
This is now explicitly documented with more clarity, here: https://feathers-pinia.pages.dev/guide/use-clones.html#automatic-patch-diffing

**Comment by emmanuelgeoffray** [comment]
It would be nice to have this on `modelInstance.save` too !

Correct me if I'm wrong but right now this works only with `save_user`, not `modelInstance.save`.

**Comment by marshallswain** [comment]
The diffing feature is unique to useClones; however, you can already pass an object to params.data when calling instance.patch.  That object will be used for the request data.

I do like the idea of enabling a diffing feature on patch, though, using the same logic as in useClones (meaning diff deep and send top-level keys)

**Comment by marshallswain** [comment]
I actuallly used to diff in feathers-vuex but I ended up removing the feature because it was pretty slow on Vuex-stored data.  With Vue 3 it would be fast.  Since the first argument to patch is the params object, we have to put it in a key of params I think.  

Instance.patch({ diff: key | key[] | object})

**Comment by marshallswain** [comment]
It would also work for instance.save, since that just passes the params to patch

**Comment by marshallswain** [comment]
Actually, maybe we can use params.data with that’s same API.  Also, this diffing algorithm is smart enough that with a small tweak it could be enabled by default on all patch requests that include params.data. It could be disabled by passing params.diff = false.  I like where this is heading.

**Comment by marshallswain** [comment]
Actually we can have two algorithms:

- remove any keys that haven’t changed, which is what currently happens
- Or include all keys if any changed

**Comment by marshallswain** [comment]
Nah.  Just the first/current algorithm. The saveWith API can be used to make sure other keys are always passed if needed.

**Comment by emmanuelgeoffray** [comment]
The `diff` property in params for patch and save seems to be the right implementation.
Easy to understand and use !

**Comment by marshallswain** [comment]
For MongoDB, making a request with dotted syntax could actually work for only sending nested data:

```js
await save_user(['name', 'profile.photo'])

// Sends out this
{
  'name': 'foo',
  'profile.photo': 'url'
}
```
