### ISSUE TITLE
No types after 0.36.3

### ISSUE THREAD

**Issue by sainf** [marshallswain/feathers-pinia#61]
Only in 0.36.3
![image](https://user-images.githubusercontent.com/1210947/188516997-ec75f897-9a5d-459f-bedd-dd5e96459e0c.png)

Adding `"types": "src/",` to package.json fixes.

Are types really added to bundled?

**Comment by gorango** [comment]
The `types` property may have been removed as a result of adding the [vite-plugin-dts](https://github.com/alloc/vite-dts).

[TypeScript docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) suggest that this prop shouldn't really be omitted:

> if your main declaration file is named `index.d.ts` and lives at the root of the package (next to `index.js`) you do not need to mark the `types` property, though it is advisable to do so.

**Comment by marshallswain** [comment]
![Screen Shot 2022-09-07 at 10 51 12 PM](https://user-images.githubusercontent.com/128857/189037212-e8c71d2a-419a-4b9c-ae0e-1401f7249de2.jpg)

@sainf Thank you for reporting!  I've published two patch releases, as shown in the screenshot.  If you could compare them and note any differences, I'd appreciate it.  Thank you!

**Comment by sainf** [comment]
Solved, Thanks!
