### ISSUE TITLE
Could not resolve "@feathersjs/rest-client" on latest

### ISSUE THREAD

**Issue by MajesticPotatoe** [marshallswain/feathers-pinia#68]
Getting the following error on latest version w/vite:

[ERROR] Could not resolve "@feathersjs/rest-client"

    node_modules/feathers-pinia/dist/feathers-pinia.mjs:5:34:
      5 │ import { FetchClient as bt } from "@feathersjs/rest-client";
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@feathersjs/rest-client" as external to exclude it from the bundle, which
  will remove this error.
  
Assuming this came about with the addition of the `ohmyrest` from pre.16

**Comment by marshallswain** [comment]
This should be resolved, now, since `@feathersjs/rest-client` has been added to the `optionalDependencies`.
