### ISSUE TITLE
idea: clientside `paginate: false` flag for `find` action

### ISSUE THREAD

**Issue by fratzinger** [marshallswain/feathers-pinia#71]
Just a quick thought:

### Problem:
`MyModel.find({...})` returns `MyModel[] | Paginated<MyModel>`.

When I need an array of values I do this:
```ts
const arrOrPaginated = MyModel.find({ ... });
const arr = Array.isArray(arrOrPaginated) ? arrOrPaginated : arrOrPaginated.data;

// now I can use arr but why so complicated?!
```

### Solution:
```ts
const arr = MyModel.find({ query: {}, paginate: false });
// I can safely know, that `arr` is an array
```

The `asArray` flag could do exactly this:
```ts
const arr = Array.isArray(arrOrPaginated) ? arrOrPaginated : arrOrPaginated.data;
```

Even the type could be inferred to be an array (pretty much as `paginate: false` on the server side).

Where to put this logic? Maybe here: https://github.com/marshallswain/feathers-pinia/blob/main/src/service-store/make-actions.ts#L112

We have `afterFind`, but it does not know about `params`. The signature of afterFind probably should be: `afterFind(response, params)` anyways.

**Comment by marshallswain** [comment]
Coming back to this, I'd honestly prefer to see the response always come back with the array on the `data` key.

```ts
const response = Model.find({ query : {}, paginate: false })
Object.keys(response) // --> ['data']
```

**Comment by marshallswain** [comment]
Find results are normalized to `data` as I mentioned on Jan 3.
