### ISSUE TITLE
useFind keeps previous queries in cache

### ISSUE THREAD

**Issue by emmanuelgeoffray** [marshallswain/feathers-pinia#72]
I've found an issue when changing query : previous queries are kept in cache inside useFind if a property is not explicitly changed 

```
// Updates the _params with everything from _newParams except `$limit` and `$skip`
export function updateParamsExcludePage(_params: Ref<FindClassParams>, _newParams: MaybeRef<FindClassParams>) {
  _newParams = unref(_newParams)
  const query = _.omit(_newParams.query, '$limit', '$skip')
  const newParams = _.omit(_params.value, 'store', 'query')
  Object.assign(_params.value.query, query)
  Object.assign(_params.value, newParams)
}
```

if _params.value.query is { firstname: Emmanuel } and _newParams.value.query is { age: 16 }, resulting query is { firstname: Emmanuel , age: 16 }
I think expected behavior is to have resulting query be { age: 16 }

I encountered this issue when using a computed params.

**Comment by marshallswain** [comment]
I think it will solve the problem to sync the params just before queries go out, including using `delete` on the old keys, where needed.

**Comment by emmanuelgeoffray** [comment]
I'm not sure you need to recursively look for old keys and delete.
I think we want to `pick` instead of `omit`. what do you think ?

```
_params.value.query = {
  ..._newParams.query,
  ..._pick(_params.value.query, ['$limit', '$skip'])
}
```

**Comment by marshallswain** [comment]
Fixed: https://github.com/marshallswain/feathers-pinia/releases/tag/v2.0.0-pre.10
