### ISSUE TITLE
Importing or dynamically inherit feathers dove schema as Model instance default?

### ISSUE THREAD

**Issue by corepay** [marshallswain/feathers-pinia#73]
Hi Marshall,

Well time to upgrade or at least start poking a stick at Feathers Dove with your Feathers Pinia lib.  Real cool everything i read in your docs and not significant changes from the feathers-vuex pattern.  Looks easy, good docs so far everything very readable and relatable.

So, i might have missed it - was hoping to find a param in the Models something like `inheritSchema` that would setup my instance default to whatever schema I create in Feathers for the service.  Feathers Vuex saves a ton of time and boilerplate but the one thing - the only thing - I found tedious was keeping my feathers db models in sync with my feathers-vuex models.

Reading about dove schemas the first thing came to mind was yay now I can have a source of truth / write once and everything is magic from there.
 
I'm sure you've considered this.  any feedback or link to look at?

**Comment by marshallswain** [comment]
> I'm sure you've considered this.

Full disclosure: I just tested out the client types for the first time this week. 😁 

My current plan is to release 1.0 without integration of the types, then look further into how to take advantage of them.  I think we might be able to use `implements UserData`, etc, when declaring our classes.  So the types would define the interface and you'd use the class to define the default values.

**Comment by marshallswain** [comment]
Version 2.0 pre-release is now out.  The examples show how to use Dove types with your Models and stores.  You can see examples on the What's New page starting here: https://v2.feathers-pinia.pages.dev/guide/whats-new.html#model-functions-not-classes-%F0%9F%94%AE

Worth noting, the Dove types are just types, so you still specify default values using an object using the `useInstanceDefaults` utility, which is documented, here: https://v2.feathers-pinia.pages.dev/guide/model-functions-shared.html#useinstancedefaults
