### ISSUE TITLE
Auth store type does not match function - setLoaded

### ISSUE THREAD

**Issue by engineertdog** [marshallswain/feathers-pinia#74]
The `setLoaded` function's type definition and function definition differ. 

Interface - https://github.com/marshallswain/feathers-pinia/blob/main/src/define-auth-store.ts#L53
Function - https://github.com/marshallswain/feathers-pinia/blob/main/src/define-auth-store.ts#L125

The question is, which one should be the correct one to use? Should `setLoaded` always set `isLoading` to false? Or is the type definition correct in that the user should be able to toggle `isLoading`?

**Comment by marshallswain** [comment]
This issue is fixed by version 2.0 and the new useAuth utility: https://v2.feathers-pinia.pages.dev/. Thanks for reporting
