### ISSUE TITLE
useFind does not add id to results when using $select

### ISSUE THREAD

**Issue by MajesticPotatoe** [marshallswain/feathers-pinia#79]
I have a very basic query that uses $select:
```js
const { data, find } = store.useFind({
  query: computed(() => ({
    $select: ['Text', 'Value'],
  })),
})
```
The server side data retrieval is as expected (server query always returns the ID field from feathers, even if not specified in $select query)
The local query however does not return the `id` in the data set causing it to set a `_tempId` instead.

**Comment by marshallswain** [comment]
This has been fixed / worked around in https://github.com/marshallswain/feathers-pinia/releases/tag/v1.0.0-pre.21.  It will now return the entire instance from the local `findInStore` getter while keeping compatibility with the Feathers API implementation of `$select`.
