### ISSUE TITLE
Whitelisted param with find returns only empty array

### ISSUE THREAD

**Issue by martinfruehmorgen** [marshallswain/feathers-pinia#8]
Hello,

(like already on discord): Using feathers-pinia with a whitelisted query argument does only return an empty value.

If you change the whitelist.test.ts in /tests with the following code you see the issue.

Thanks,
Martin
```

  test('enables custom query params for the find getter', async () => {
    const { defineStore, BaseModel } = setupFeathersPinia({
      clients: { api },
      whitelist: ['$regex'],
    })

    const useMessagesService = defineStore({ servicePath: 'messages' })
    const messagesService = useMessagesService(pinia)

    await messagesService.create({ text: 'test' })
    await messagesService.create({ text: 'yo!' })

    const dataREGEX = messagesService.findInStore({ query: { $regex: 'test' } }).data
    const dataNOREGEX = messagesService.findInStore({ query: {} }).data

    console.log('CHECK DATA regex', dataREGEX) // -> NO DATA RETURNED
    console.log('CHECK DATA NOregex', dataNOREGEX) // -> DATA RETURNED

    expect(Array.isArray(dataREGEX)).toBeTruthy()
    expect(Array.isArray(dataNOREGEX)).toBeTruthy()
  })
```

**Comment by marshallswain** [comment]
Thanks for reporting this.  It will be a little while before I can look into this.  Seems like the $regex operator should work the same as with Feathers-Vuex, so this might be a regression bug.

**Comment by martinfruehmorgen** [comment]
Hello,

seems like
https://github.com/marshallswain/feathers-pinia/blob/80a9f2a58df1cfd819e971439798fae34a202963/src/service-store/make-getters.ts#L63
filters out the values. Any idea how to handle this?

Thanks!
Martin

**Comment by marshallswain** [comment]
@martinfruehmorgen I figured this one out.  I had made a mistake in the query syntax.  I have updated the test with your code to insert a couple of documents.  With the fixed query, I'm able to test that the proper document is returned.  Try that out and feel free to reopen if there's still an issue.

**Comment by marshallswain** [comment]
It's surprising to hear that `$modify` works in Feathers-Vuex.  It
shouldn't without manually adding a handler for `$modify` to the
underlying `sift` module.  I've never tried setting up a custom handler,
but there are docs for it at https://npmjs.com/package/sift.

The `paramsForServer` utils from feathers-graph-populate should just
work.  Are you finding otherwise?

On December 3, 2021, GitHub ***@***.***> wrote:
> Hi @marshallswain <https://github.com/marshallswain>
>  Thanks for the fix. It works for the $regex parameter as the sift-
> package supports that.
>
> In my case, I am using feathers-objection with the $modify parameter.
> When using that, the results are still empty... When comparing the
> feathers-pinia code with feathers-vuex (where that works) I can't find
> a way to fix that.
>  Also, do you plan to support paramsForServer (like with feathers
> Vuex)?
>
> Thanks for any hint!
>  Martin
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/marshallswain/feathers-pinia/issues/8#issuecomment-
985682595>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAA7OWPRHEK4FBI2UCOG4ODUPD2D7ANCNFSM5HGAO76Q>.

**Comment by martinfruehmorgen** [comment]
Hi @marshallswain
Thanks. Yes, with feathers-vuex all the params like $eager or $modify work out of the box.
I think it has to do with a earlier (less strict?) version of the sift module as it goes through the same routines like in feathers-pinia.
I am now deleting all unsupported query params hardcoded in the findInStore method of feathers-pinia.

Thanks
Martin
