### ISSUE TITLE
Restore compatibility with `findInStore` using `$and`

### ISSUE THREAD

**Issue by marshallswain** [marshallswain/feathers-pinia#86]
![Screen Shot 2022-11-08 at 9 19 35 PM](https://user-images.githubusercontent.com/128857/200737562-b9c7d0cb-9f5b-428c-884a-e2791b9a7546.jpg)

**Comment by philipimperato** [comment]
Is this a `feathers-pinia` issue? 

If you're going to use `feathers-casl` you're going to have to manually add this on the dove side. 

```
export class MyCustomService extends MongoDBService {}
export const getOptions = (app) => {
  return {
    paginate: app.get('paginate'),
    Model: app.get('mongodbClient').then((db) => db.collection('my-custom-service')),
    filters: { $and: true } <- HERE
  }
}
```

**Comment by marshallswain** [comment]
I think we should automatically add $and to any service passed to FeathersModel or pre-service.

**Comment by philipimperato** [comment]
Just to keep you in the loop. I had mentioned this in the Dove discord and Daffl, Fratzinger were in a agreement that `$and` will be added to the native dove setup. I was running into schema validation issues on nested $and / $or.
