### ISSUE TITLE
setupInstance never called on items that are automatically added to store after a find action

### ISSUE THREAD

**Issue by tasker204** [marshallswain/feathers-pinia#88]
I can see that the setupInstance method is called from the BaseModel constructor, but it doesn't appear to be called for items returned from an API call that are added to the store automatically. Is this expected?

**Comment by marshallswain** [comment]
@tasker204 it should be called for all items.  Here's a "stack trace":

- in `handleFindResponse` it calls [addOrUpdate](https://github.com/marshallswain/feathers-pinia/blob/main/src/service-store/make-actions.ts#L100)
- in `addOrUpdate` it calls [addOrMergeToStore](https://github.com/marshallswain/feathers-pinia/blob/main/src/service-store/make-actions.ts#L290) There's some conditional logic there could could skip that part, so you'd want to hit it with a breakpoint before the conditional if you're debugging an issue.
- in `addOrMergeToStore` it calls [new Model(data)](https://github.com/marshallswain/feathers-pinia/blob/main/src/service-store/make-actions.ts#L461)
- If you have `setupInstance` defined on the Model, it will be run.

**Comment by marshallswain** [comment]
Feel free to reopen if there is more to discuss.  Have a great day!
